# Generated by Django 3.0.3 on 2020-03-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cpf',
            field=models.CharField(default=1, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
